clone_depth: 50

image: Visual Studio 2017

branches:
    only:
        - master

cache:
    - c:\tools\vcpkg\installed\

environment:
    BOOST_ROOT: C:\Libraries\boost_1_67_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14.1

install:
    - git submodule update --init --recursive
    - vcpkg install sdl2:x64-windows sdl2-mixer:x64-windows

platform: x64

configuration:
    - Debug
    - Release

before_build:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 15 2017 Win64"
    - cd ..

build:
    parallel: true
    project: build/RigelEngine.sln
    verbosity: minimal

test_script:
    - cd build
    - ctest

after_build:
  - 7z a rigel_build.zip C:\projects\rigelengine\build\src\%CONFIGURATION%\RigelEngine.exe C:\projects\rigelengine\build\src\%CONFIGURATION%\SDL*.dll %BOOST_LIBRARYDIR%\boost_program_options-vc141-mt%BOOST_DBG_MARKER%-x64-1_67.dll

artifacts:
    - path: rigel_build.zip
      name: RigelBuild
